name: cached_network_image_web
description: Web implementation of CachedNetworkImage
version: 1.1.0
homepage: https://github.com/Baseflow/flutter_cached_network_image
publish_to: none
environment:
  sdk: ^3.0.0
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: https://github.com/tentram/flutter_cache_manager
      ref: develop
      path: flutter_cache_manager
  cached_network_image_platform_interface:
    git:
      url: https://github.com/tentram/flutter_cached_network_image
      ref: develop
      path: cached_network_image_platform_interface

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter