name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.3
publish_to: none

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager:
    git:
      url: https://github.com/tentram/flutter_cache_manager
      ref: develop
      path: flutter_cache_manager

  octo_image:
    git:
      url: https://github.com/tentram/octo_image

  cached_network_image_platform_interface:
    git:
      url: https://github.com/tentram/flutter_cached_network_image
      ref: develop
      path: cached_network_image_platform_interface

  cached_network_image_web:
    git:
      url: https://github.com/tentram/flutter_cached_network_image
      ref: develop
      path: cached_network_image_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  flutter_lints: ^2.0.3
  file: ^7.0.0

environment:
  flutter: ">=3.3.0"
  sdk: ">=3.0.0 <4.0.0"
